---
title: "MATH560 R Lab 1"
author: "Jared Andreatta"
date: "`r Sys.Date()`"
output:
  pdf_document:
    df_print: paged
---

## 2.3.1 Basic commands

### Vectors

```{r}
# Defining vector
x <- c(1, 7, 5, 8)
y <- c(8, 9, 3, 2)
x
y

# Length of vector
length(x)
length(y)

# Vector addition
x+y

# ls and rm
ls() # List of all objects in environment
rm(x,y) # Delete vectors
rm(list = ls()) # Delete entire list
```

### Matrices

```{r}
# Help 
?matrix

# Defining matrix
X <- matrix(c(1,2,3,4),2,2)
X
X_byrow <- matrix(c(1,2,3,4),2,2,byrow = TRUE) # Entries go by row now, not columns
X_byrow

# Some math operations
X_sqrt <- sqrt(X)
X_sqrt
X_sq <- X^2
X_sq 

```
### Some statistics

```{r}
# rnorm: generate normal random vector

set.seed(150) # Reproduce same random vectors

x <- rnorm(50) # n=50, mu=0, std=1
y <- x + rnorm(50, mean=50, sd=.1)
cor(x,y) # Correlation between random vectors

# Statistics
mean(y) # Sample mean
var(y) # Sample variance
sqrt(var(y)) # Sample std deviation
sd(y) #Also sample std deviation

```
## 2.3.2 Graphics

### Basic plotting

```{r}
x <- rnorm(100)
y <- rnorm(100)

plot(x,y)# Basic plot of x vs y

plot(x,y,
     xlab="x-axis",
     ylab="y-axis",
     main="Plot of x vs y") # Plot with labels

# Creating pdf
pdf("example.pdf")
plot(x,y, col="orange")
dev.off() # Done with plotting

# Sequences
x <- seq(1,10) #seq function
x <- 1:10 # Easier way to create sequence
x
x <- seq(-pi, pi, length=50) # Evenly spaced sequence of numbers between (-pi,pi)
x
```
### Contour plots

```{r}
y <- x
f <- outer(x, y, function(x, y) cos(y) / (1 + x^2))
contour(x, y, f)

# Note: 3 args for contour:
# 1. x vals
# 2. y vals
# 3. matrix of corresponding function values of the coordinate pair (x,y)

plot.new()

contour(x, y, f, nlevels = 45, add = T)
fa <- (f - t(f)) / 2
contour(x, y, fa, nlevels = 15)
```


### Image function

```{r}
image(x, y, fa) # Creates a heatmap where color depends on z vals
persp(x, y, fa) # Creates 3d plots
persp(x, y, fa, theta = 30)
persp(x, y, fa, theta = 30, phi = 20) # theta and phi params control angle at which we view the 3d plots
persp(x, y, fa, theta = 30, phi = 70)
persp(x, y, fa, theta = 30, phi = 40)
```

## 2.3.3 Indexing data

```{r}
A <- matrix(1:16, 4, 4)
A

A[2,3] #i=2, j=3

A[c(1, 3), c(2, 4)] # A_12, A_14, A_32, A_34

A[1:3, 2:4] # Indexing rows 1-3 and cols 2-4

A[1:2, ] # First two rows, all cols
A[, 1:2] # All rows, first two cols

# Note: R treats any column or row as a vector
A[1,] # First row vector of A
A[,1] # First col vector of A

A[-c(1,3), -c(2,3)] # Negative indexing removes rows 1 and 3, cols 2 and 3

# Dimension of matrix
dim(A)

```

## 2.3.4 Loading Data

```{r}
# Loading Auto data
auto <- read.table("Auto.data")
View(auto) # View in separate window
head(auto)

auto <- read.table("Auto.data", header = TRUE, na.strings = "?", stringsAsFactors = TRUE)
# Notes:
# header = TRUE : Indicate to use first row of dataset as variable names
# na.strings = "?" : Indicates that na vals == "?" in the data
# stringsAsfactors = TRUE : Indicate that any string vars are qualitative
head(auto)

# CSV data
auto = read.csv("Auto.csv", na.strings = TRUE, stringsAsFactors = TRUE)
View(auto)
dim(auto)
names(auto) # Var names
```

## 2.3.5 Additional numerical and graphical methods

### Plotting from datasets

```{r}
# We can reference variables from the dataset with $
plot(auto$cylinders, auto$mpg)

# Alternatively, we can use attach() to access the variables of auto
attach(auto)
plot(cylinders,mpg)

# Cylinders is a categorical variable, so we can change it to a qualitative variable
auto$cylinders <- as.factor(cylinders)

# Modifying plots
plot(cylinders, mpg)
plot(cylinders, mpg, col = "red") # Changes points to red color
plot(cylinders, mpg, col = "red", varwidth = TRUE) 
plot(cylinders, mpg, col = "red", varwidth = T,
 horizontal = T)
plot(cylinders, mpg, col = "red", varwidth = T,
 xlab = "cylinders", ylab = "MPG")

# Note: Says varwidth and horizontal are not params? What to do about this?

# Histograms
hist(mpg)
hist(mpg, col="red") # Change color of bars to red
hist(mpg, col="red", breaks=15) # Change amount of bars

# Scatterplot matrices using pairs()
pairs(auto)
pairs(
 ~mpg + displacement + horsepower + weight + acceleration,
 data = auto
 ) # Specify a subset of variables for the plot

# identify() function
plot(horsepower, mpg)
# 3 args: x var, y var, and var we want to see printed for each point
identify(horsepower, mpg, name)
```

### Numerical functions

```{r}
# Summary table for each variable in the dataset
summary(auto)
# We can also do a summary of a single var
summary(mpg)

# Saving and loading history 
#savehistory()
#loadhistory()
```














