---
title: "R Lab 8"
author: "Jared Andreatta"
date: "`r Sys.Date()`"
output: 
  pdf_document:
     toc: false
---

# 7.8.2 Splines

Use the splines library. 
```{r}
library(splines)
library(ISLR2)
attach(Wage)
agelims <- range(age)
age.grid <- seq(from = agelims [1], to = agelims [2])
# Regression spline fit with 3 knots
# Note the bs() function generates a matrix of basis functions for splines with
# a specified set of knots.
fit <- lm(wage ~ bs(age , knots = c(25, 40, 60)), data = Wage)
pred <- predict(fit , newdata = list(age = age.grid), se = T)
plot(age , wage , col = "gray")
lines(age.grid , pred$fit , lwd = 2)
lines(age.grid , pred$fit + 2 * pred$se, lty = "dashed")
lines(age.grid , pred$fit - 2 * pred$se, lty = "dashed")

dim(bs(age , knots = c(25, 40, 60)))
dim(bs(age , df = 6))
# R chooses 33.8, 42, and 51 as knots, which correspond to 25, 50, and 75
# quantiles.
attr(bs(age , df = 6), "knots")

### Fitting with a natural spline with 4 Dfs via ns()
fit2 <- lm(wage ~ ns(age , df = 4), data = Wage)
pred2 <- predict(fit2 , newdata = list(age = age.grid),
                 se = T)
lines(age.grid , pred2$fit , col = "red", lwd = 2)

### Fitting with smoothing splines via smooth.spline()
plot(age , wage , xlim = agelims , cex = .5, col = "darkgrey")
title("Smoothing Spline")
fit <- smooth.spline(age , wage , df = 16)
fit2 <- smooth.spline(age , wage , cv = TRUE)
fit2$df

lines(fit , col = "red", lwd = 2)
lines(fit2 , col = "blue", lwd = 2)
legend("topright", legend = c("16 DF", "6.8 DF"),
col = c("red", "blue"), lty = 1, lwd = 2, cex = .8)

### Fitting with local regressions via LOESS
plot(age , wage , xlim = agelims , cex = .5, col = "darkgrey")
title("Local Regression")
fit <- loess(wage ~ age , span = .2, data = Wage)
fit2 <- loess(wage~age , span = .5, data = Wage)
lines(age.grid , predict(fit , data.frame(age = age.grid)),      
      col = "red", lwd = 2)
lines(age.grid , predict(fit2 , data.frame(age = age.grid)),      
      col = "blue", lwd = 2)
legend("topright", legend = c("Span = 0.2", "Span = 0.5"),
        col = c("red", "blue"), lty = 1, lwd = 2, cex = .8)
```

# 7.8.3 GAMs

```{r}
# Fitting GAM with natural spline basis functions
gam1 <- lm(wage ~ ns(year , 4) + ns(age , 5) + education ,
data = Wage)

library(gam)

# We can use s() to indicate that we want to use smoothing splines
gam.m3 <- gam(wage ~ s(year , 4) + s(age , 5) + education ,
data = Wage)
# Plotting gam object
par(mfrow = c(1, 3))
plot(gam.m3 , se = TRUE , col = "blue")
# Explicitly calling plot.Gam()
plot.Gam(gam1 , se = TRUE , col = "red")

# Performing ANOVA to see which fit is best
# Adding spline function onto year doesn't help
gam.m1 <- gam(wage ~ s(age , 5) + education , data = Wage) # No year for M1
gam.m2 <- gam(wage ~ year + s(age , 5) + education ,              
              data = Wage) # Linear function of year for M2
anova(gam.m1 , gam.m2 , gam.m3 , test = "F") # M3 has a spline function for year

summary(gam.m3)

# Producing predictions with M2
preds <- predict(gam.m2 , newdata = Wage)

# Using lo() for local regressions
gam.lo <- gam( wage ~ s(year , df = 4) + lo(age , span = 0.7) + education ,
              data = Wage)
plot(gam.lo , se = TRUE , col = "green")

# Interaction term inside lo()
gam.lo.i <- gam(wage ~ lo(year , age , span = 0.5) + education ,
data = Wage)

# akima library to plot 2D surface
library(akima)
plot(gam.lo.i)

```




